version: '3.8'
services:
  front:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    depends_on:
      - backend
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 5001:5001
    container_name: express-container